### ISSUE TITLE
violations dataset seems to have a lot of NA in the police sector column

### ISSUE THREAD

**Issue by novica** [discindo/semejno_nasilstvo#5]

**Comment by teofiln** [comment]
This is actually a pain. I because the main unit of observation is Article, but the breakdowns are by categories that differ a lot. So we need new translation tables for some of them. Then handle the data partially...

![image](https://user-images.githubusercontent.com/2613403/204018449-7c4ec2cb-89f9-4247-a5ab-1967a26086a9.png)

**Comment by teofiln** [comment]
should be ok now.
